
################### English Navigation ########################
[[main]]
name = "about"
url = "#about"
weight = 1

[[main]]
name = "services"
url = "#services"
weight = 2
hasChildren = true

[[main]]
parent = "services"
name = "Cybersecurity"
url = "#cybersecurity"
weight = 1

[[main]]
parent = "services"
name = "Automation & Tools"
url = "#automation-tools"
weight = 2

[[main]]
parent = "services"
name = "Research & Development"
url = "#research-development"
weight = 3

[[main]]
name = "portfolio"
url = "#portfolio"
weight = 3

#[[main]]
#name = "team"
#url = "#team"
#weight = 4

[[main]]
name = "pricing"
url = "#pricing"
weight = 4

#[[main]]
#name = "tools"
#url = "#developed-tools"
#weight = 5
#hasChildren = true

#[[main]]
#parent = "tools"
#name = "Cybersecurity Tools"
#url = "#cybersecurity-tools"
#weight = 1

#[[main]]
#parent = "tools"
#name = "Trading Tools"
#url = "#trading-tools"
#weight = 2

[[main]]
name = "blog"
url = "#blog"
weight = 5

[[main]]
name = "contact"
url = "#contact"
weight = 6
